/****************************************************************************
 * arch/arm/src/rm57/hardware/rm57_ethernet.h
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.  The
 * ASF licenses this file to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance with the
 * License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.  See the
 * License for the specific language governing permissions and limitations
 * under the License.
 *
 ****************************************************************************/

/* EMAC / EMAC Control Module / MDIO register layout for the RM57L843,
 * transcribed from SPNU562A chapter 31 ("EMAC/MDIO Module") and
 * cross-checked against TI's HALCoGen HL_hw_emac.h, HL_hw_emac_ctrl.h and
 * HL_hw_mdio.h.
 *
 * This device implements a single-core CPSW-lite subsystem: only "core 0"
 * exists, so only the C0xxx EMAC Control registers and USERACCESS0 /
 * USERPHYSEL0 MDIO registers are meaningful.  HALCoGen's EMAC_CTRL_CnRXEN()
 * style macros are inherited from a multi-core EMAC variant used on other
 * TI parts and do not apply here - this header only defines the C0
 * registers that actually exist on RM57L843.
 *
 * NOTE: HALCoGen's HL_hw_emac.h defines EMAC_NETOCTETS at offset 0x208,
 * but SPNU562A Section 31.5.50.33 documents the Network Octet Frames
 * Register (NETOCTETS) at offset 0x280; offset 0x208 is actually
 * RXMCASTFRAMES (Section 31.5.50.3).  This appears to be a transcription
 * error in the HALCoGen header.  This file uses the TRM-documented value.
 */

#ifndef __ARCH_ARM_SRC_RM57_HARDWARE_RM57_ETHERNET_H
#define __ARCH_ARM_SRC_RM57_HARDWARE_RM57_ETHERNET_H

/****************************************************************************
 * Included Files
 ****************************************************************************/

#include <nuttx/config.h>
#include <stdint.h>
#include "hardware/rm57l843_memorymap.h"

/****************************************************************************
 * Pre-processor Definitions
 ****************************************************************************/

/* CPPI buffer descriptor memory ********************************************/

/* 8KB internal CPPI RAM, holding 4-word (16-byte) buffer descriptors.
 * Shared between the TX and RX descriptor rings by software convention;
 * the hardware does not partition it.
 */

#define RM57_EMAC_CPPI_RAM_SIZE      8192
#define RM57_EMAC_DESC_SIZE          16     /* 4 words per descriptor */
#define RM57_EMAC_MAX_DESC           (RM57_EMAC_CPPI_RAM_SIZE / RM57_EMAC_DESC_SIZE)

/* EMAC Control Module Register Offsets (base RM57_EMAC_CTRL_BASE) *********/

/* SPNU562A Table 31-10.  Only channel 0 (C0) registers exist on this
 * device; this device has no C1/C2 cores.
 */

#define RM57_EMAC_CTRL_REVID_OFFSET         0x00
#define RM57_EMAC_CTRL_SOFTRESET_OFFSET     0x04
#define RM57_EMAC_CTRL_INTCONTROL_OFFSET    0x0c
#define RM57_EMAC_CTRL_C0RXTHRESHEN_OFFSET  0x10
#define RM57_EMAC_CTRL_C0RXEN_OFFSET        0x14
#define RM57_EMAC_CTRL_C0TXEN_OFFSET        0x18
#define RM57_EMAC_CTRL_C0MISCEN_OFFSET      0x1c
#define RM57_EMAC_CTRL_C0RXTHRESHSTAT_OFFSET 0x40
#define RM57_EMAC_CTRL_C0RXSTAT_OFFSET      0x44
#define RM57_EMAC_CTRL_C0TXSTAT_OFFSET      0x48
#define RM57_EMAC_CTRL_C0MISCSTAT_OFFSET    0x4c
#define RM57_EMAC_CTRL_C0RXIMAX_OFFSET      0x70
#define RM57_EMAC_CTRL_C0TXIMAX_OFFSET      0x74

/* EMAC Control Module Register Addresses ***********************************/

#define RM57_EMAC_CTRL_REVID         (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_REVID_OFFSET)
#define RM57_EMAC_CTRL_SOFTRESET     (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_SOFTRESET_OFFSET)
#define RM57_EMAC_CTRL_INTCONTROL    (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_INTCONTROL_OFFSET)
#define RM57_EMAC_CTRL_C0RXTHRESHEN  (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0RXTHRESHEN_OFFSET)
#define RM57_EMAC_CTRL_C0RXEN        (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0RXEN_OFFSET)
#define RM57_EMAC_CTRL_C0TXEN        (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0TXEN_OFFSET)
#define RM57_EMAC_CTRL_C0MISCEN      (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0MISCEN_OFFSET)
#define RM57_EMAC_CTRL_C0RXTHRESHSTAT (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0RXTHRESHSTAT_OFFSET)
#define RM57_EMAC_CTRL_C0RXSTAT      (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0RXSTAT_OFFSET)
#define RM57_EMAC_CTRL_C0TXSTAT      (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0TXSTAT_OFFSET)
#define RM57_EMAC_CTRL_C0MISCSTAT    (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0MISCSTAT_OFFSET)
#define RM57_EMAC_CTRL_C0RXIMAX      (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0RXIMAX_OFFSET)
#define RM57_EMAC_CTRL_C0TXIMAX      (RM57_EMAC_CTRL_BASE + RM57_EMAC_CTRL_C0TXIMAX_OFFSET)

/* EMAC_CTRL_SOFTRESET */

#define EMAC_CTRL_SOFTRESET_RESET    (1 << 0)

/* EMAC_CTRL_INTCONTROL */

#define EMAC_CTRL_INTCONTROL_INTPACEEN_SHIFT 16
#define EMAC_CTRL_INTCONTROL_INTPACEEN_MASK  (3 << EMAC_CTRL_INTCONTROL_INTPACEEN_SHIFT)
#define EMAC_CTRL_INTCONTROL_INTPRESCALE_SHIFT 0
#define EMAC_CTRL_INTCONTROL_INTPRESCALE_MASK  (0xfff << EMAC_CTRL_INTCONTROL_INTPRESCALE_SHIFT)

/* EMAC_CTRL_C0RXTHRESHEN / C0RXEN / C0TXEN - one bit per DMA channel 0-7 */

#define EMAC_CTRL_C0CHEN(n)          (1 << (n))

/* EMAC_CTRL_C0MISCEN / C0MISCSTAT - Section 31.3.7 */

#define EMAC_CTRL_C0MISC_USERINT0EN  (1 << 0)
#define EMAC_CTRL_C0MISC_LINKINT0EN  (1 << 1)
#define EMAC_CTRL_C0MISC_HOSTPENDEN  (1 << 2)
#define EMAC_CTRL_C0MISC_STATPENDEN  (1 << 3)

/* MDIO Register Offsets (base RM57_MDIO_BASE) ******************************/

#define RM57_MDIO_REVID_OFFSET           0x00
#define RM57_MDIO_CONTROL_OFFSET         0x04
#define RM57_MDIO_ALIVE_OFFSET           0x08
#define RM57_MDIO_LINK_OFFSET            0x0c
#define RM57_MDIO_LINKINTRAW_OFFSET      0x10
#define RM57_MDIO_LINKINTMASKED_OFFSET   0x14
#define RM57_MDIO_USERINTRAW_OFFSET      0x20
#define RM57_MDIO_USERINTMASKED_OFFSET   0x24
#define RM57_MDIO_USERINTMASKSET_OFFSET  0x28
#define RM57_MDIO_USERINTMASKCLEAR_OFFSET 0x2c
#define RM57_MDIO_USERACCESS0_OFFSET     0x80
#define RM57_MDIO_USERPHYSEL0_OFFSET     0x84
#define RM57_MDIO_USERACCESS1_OFFSET     0x88
#define RM57_MDIO_USERPHYSEL1_OFFSET     0x8c

/* MDIO Register Addresses ***************************************************/

#define RM57_MDIO_REVID              (RM57_MDIO_BASE + RM57_MDIO_REVID_OFFSET)
#define RM57_MDIO_CONTROL            (RM57_MDIO_BASE + RM57_MDIO_CONTROL_OFFSET)
#define RM57_MDIO_ALIVE              (RM57_MDIO_BASE + RM57_MDIO_ALIVE_OFFSET)
#define RM57_MDIO_LINK               (RM57_MDIO_BASE + RM57_MDIO_LINK_OFFSET)
#define RM57_MDIO_LINKINTRAW         (RM57_MDIO_BASE + RM57_MDIO_LINKINTRAW_OFFSET)
#define RM57_MDIO_LINKINTMASKED      (RM57_MDIO_BASE + RM57_MDIO_LINKINTMASKED_OFFSET)
#define RM57_MDIO_USERINTRAW         (RM57_MDIO_BASE + RM57_MDIO_USERINTRAW_OFFSET)
#define RM57_MDIO_USERINTMASKED      (RM57_MDIO_BASE + RM57_MDIO_USERINTMASKED_OFFSET)
#define RM57_MDIO_USERINTMASKSET     (RM57_MDIO_BASE + RM57_MDIO_USERINTMASKSET_OFFSET)
#define RM57_MDIO_USERINTMASKCLEAR   (RM57_MDIO_BASE + RM57_MDIO_USERINTMASKCLEAR_OFFSET)
#define RM57_MDIO_USERACCESS0        (RM57_MDIO_BASE + RM57_MDIO_USERACCESS0_OFFSET)
#define RM57_MDIO_USERPHYSEL0        (RM57_MDIO_BASE + RM57_MDIO_USERPHYSEL0_OFFSET)
#define RM57_MDIO_USERACCESS1        (RM57_MDIO_BASE + RM57_MDIO_USERACCESS1_OFFSET)
#define RM57_MDIO_USERPHYSEL1        (RM57_MDIO_BASE + RM57_MDIO_USERPHYSEL1_OFFSET)

/* MDIO_CONTROL - Section 31.4.2 */

#define MDIO_CONTROL_CLKDIV_SHIFT    0
#define MDIO_CONTROL_CLKDIV_MASK     (0xffff << MDIO_CONTROL_CLKDIV_SHIFT)
#define MDIO_CONTROL_CLKDIV(n)       (((n) & 0xffff) << MDIO_CONTROL_CLKDIV_SHIFT)
#define MDIO_CONTROL_FAULTENB        (1 << 18)
#define MDIO_CONTROL_FAULT           (1 << 19)
#define MDIO_CONTROL_PREAMBLE        (1 << 20)  /* 1 = no preamble on access */
#define MDIO_CONTROL_HIGHEST_USER_CHANNEL_SHIFT 24
#define MDIO_CONTROL_HIGHEST_USER_CHANNEL_MASK  (0x1f << MDIO_CONTROL_HIGHEST_USER_CHANNEL_SHIFT)
#define MDIO_CONTROL_ENABLE          (1 << 30)
#define MDIO_CONTROL_IDLE            (1u << 31)

/* MDIO_ALIVE / MDIO_LINK - one bit per PHY address 0-31 */

#define MDIO_ALIVE_PHY(n)            (1u << (n))
#define MDIO_LINK_PHY(n)             (1u << (n))

/* MDIO_LINKINTRAW / LINKINTMASKED - bit 0 = USERPHYSEL0, bit 1 = USERPHYSEL1 */

#define MDIO_LINKINT_USERPHY0        (1 << 0)
#define MDIO_LINKINT_USERPHY1        (1 << 1)

/* MDIO_USERINTRAW / USERINTMASKED / USERINTMASKSET / USERINTMASKCLEAR -
 * bit 0 = USERACCESS0, bit 1 = USERACCESS1
 */

#define MDIO_USERINT_USERACCESS0     (1 << 0)
#define MDIO_USERINT_USERACCESS1     (1 << 1)

/* MDIO_USERACCESS0 / USERACCESS1 - Section 31.4.11 */

#define MDIO_USERACCESS_DATA_SHIFT   0
#define MDIO_USERACCESS_DATA_MASK    (0xffff << MDIO_USERACCESS_DATA_SHIFT)
#define MDIO_USERACCESS_PHYADR_SHIFT 16
#define MDIO_USERACCESS_PHYADR_MASK  (0x1f << MDIO_USERACCESS_PHYADR_SHIFT)
#define MDIO_USERACCESS_PHYADR(n)    (((n) & 0x1f) << MDIO_USERACCESS_PHYADR_SHIFT)
#define MDIO_USERACCESS_REGADR_SHIFT 21
#define MDIO_USERACCESS_REGADR_MASK  (0x1f << MDIO_USERACCESS_REGADR_SHIFT)
#define MDIO_USERACCESS_REGADR(n)    (((n) & 0x1f) << MDIO_USERACCESS_REGADR_SHIFT)
#define MDIO_USERACCESS_ACK          (1 << 29)
#define MDIO_USERACCESS_WRITE        (1 << 30)
#define MDIO_USERACCESS_READ         (0 << 30)
#define MDIO_USERACCESS_GO           (1u << 31)

/* MDIO_USERPHYSEL0 / USERPHYSEL1 - Section 31.4.12 */

#define MDIO_USERPHYSEL_PHYADRMON_SHIFT 0
#define MDIO_USERPHYSEL_PHYADRMON_MASK  (0x1f << MDIO_USERPHYSEL_PHYADRMON_SHIFT)
#define MDIO_USERPHYSEL_PHYADRMON(n)    (((n) & 0x1f) << MDIO_USERPHYSEL_PHYADRMON_SHIFT)
#define MDIO_USERPHYSEL_LINKINTENB      (1 << 6)
#define MDIO_USERPHYSEL_LINKSEL         (1 << 7)

/* EMAC Register Offsets (base RM57_EMAC_BASE) ******************************/

#define RM57_EMAC_TXREVID_OFFSET     0x000
#define RM57_EMAC_TXCONTROL_OFFSET   0x004
#define RM57_EMAC_TXTEARDOWN_OFFSET  0x008
#define RM57_EMAC_RXREVID_OFFSET     0x010
#define RM57_EMAC_RXCONTROL_OFFSET   0x014
#define RM57_EMAC_RXTEARDOWN_OFFSET  0x018
#define RM57_EMAC_TXINTSTATRAW_OFFSET    0x080
#define RM57_EMAC_TXINTSTATMASKED_OFFSET 0x084
#define RM57_EMAC_TXINTMASKSET_OFFSET    0x088
#define RM57_EMAC_TXINTMASKCLEAR_OFFSET  0x08c
#define RM57_EMAC_MACINVECTOR_OFFSET     0x090
#define RM57_EMAC_MACEOIVECTOR_OFFSET    0x094
#define RM57_EMAC_RXINTSTATRAW_OFFSET    0x0a0
#define RM57_EMAC_RXINTSTATMASKED_OFFSET 0x0a4
#define RM57_EMAC_RXINTMASKSET_OFFSET    0x0a8
#define RM57_EMAC_RXINTMASKCLEAR_OFFSET  0x0ac
#define RM57_EMAC_MACINTSTATRAW_OFFSET   0x0b0
#define RM57_EMAC_MACINTSTATMASKED_OFFSET 0x0b4
#define RM57_EMAC_MACINTMASKSET_OFFSET   0x0b8
#define RM57_EMAC_MACINTMASKCLEAR_OFFSET 0x0bc
#define RM57_EMAC_RXMBPENABLE_OFFSET     0x100
#define RM57_EMAC_RXUNICASTSET_OFFSET    0x104
#define RM57_EMAC_RXUNICASTCLEAR_OFFSET  0x108
#define RM57_EMAC_RXMAXLEN_OFFSET        0x10c
#define RM57_EMAC_RXBUFFEROFFSET_OFFSET  0x110
#define RM57_EMAC_RXFILTERLOWTHRESH_OFFSET 0x114
#define RM57_EMAC_RXFLOWTHRESH_OFFSET(n) (0x120 + ((n) << 2))
#define RM57_EMAC_RXFREEBUFFER_OFFSET(n) (0x140 + ((n) << 2))
#define RM57_EMAC_MACCONTROL_OFFSET  0x160
#define RM57_EMAC_MACSTATUS_OFFSET   0x164
#define RM57_EMAC_EMCONTROL_OFFSET   0x168
#define RM57_EMAC_FIFOCONTROL_OFFSET 0x16c
#define RM57_EMAC_MACCONFIG_OFFSET   0x170
#define RM57_EMAC_SOFTRESET_OFFSET   0x174
#define RM57_EMAC_MACSRCADDRLO_OFFSET 0x1d0
#define RM57_EMAC_MACSRCADDRHI_OFFSET 0x1d4
#define RM57_EMAC_MACHASH1_OFFSET    0x1d8
#define RM57_EMAC_MACHASH2_OFFSET    0x1dc
#define RM57_EMAC_BOFFTEST_OFFSET    0x1e0
#define RM57_EMAC_TPACETEST_OFFSET   0x1e4
#define RM57_EMAC_RXPAUSE_OFFSET     0x1e8
#define RM57_EMAC_TXPAUSE_OFFSET     0x1ec

/* Network statistics registers - Section 31.5.50 */

#define RM57_EMAC_RXGOODFRAMES_OFFSET      0x200
#define RM57_EMAC_RXBCASTFRAMES_OFFSET     0x204
#define RM57_EMAC_RXMCASTFRAMES_OFFSET     0x208
#define RM57_EMAC_RXPAUSEFRAMES_OFFSET     0x20c
#define RM57_EMAC_RXCRCERRORS_OFFSET       0x210
#define RM57_EMAC_RXALIGNCODEERRORS_OFFSET 0x214
#define RM57_EMAC_RXOVERSIZED_OFFSET       0x218
#define RM57_EMAC_RXJABBER_OFFSET          0x21c
#define RM57_EMAC_RXUNDERSIZED_OFFSET      0x220
#define RM57_EMAC_RXFRAGMENTS_OFFSET       0x224
#define RM57_EMAC_RXFILTERED_OFFSET        0x228
#define RM57_EMAC_RXQOSFILTERED_OFFSET     0x22c
#define RM57_EMAC_RXOCTETS_OFFSET          0x230
#define RM57_EMAC_TXGOODFRAMES_OFFSET      0x234
#define RM57_EMAC_TXBCASTFRAMES_OFFSET     0x238
#define RM57_EMAC_TXMCASTFRAMES_OFFSET     0x23c
#define RM57_EMAC_TXPAUSEFRAMES_OFFSET     0x240
#define RM57_EMAC_TXDEFERRED_OFFSET        0x244
#define RM57_EMAC_TXCOLLISION_OFFSET       0x248
#define RM57_EMAC_TXSINGLECOLL_OFFSET      0x24c
#define RM57_EMAC_TXMULTICOLL_OFFSET       0x250
#define RM57_EMAC_TXEXCESSIVECOLL_OFFSET   0x254
#define RM57_EMAC_TXLATECOLL_OFFSET        0x258
#define RM57_EMAC_TXUNDERRUN_OFFSET        0x25c
#define RM57_EMAC_TXCARRIERSENSE_OFFSET    0x260
#define RM57_EMAC_TXOCTETS_OFFSET          0x264
#define RM57_EMAC_FRAME64_OFFSET           0x268
#define RM57_EMAC_FRAME65T127_OFFSET       0x26c
#define RM57_EMAC_FRAME128T255_OFFSET      0x270
#define RM57_EMAC_FRAME256T511_OFFSET      0x274
#define RM57_EMAC_FRAME512T1023_OFFSET     0x278
#define RM57_EMAC_FRAME1024TUP_OFFSET      0x27c

/* NETOCTETS: TRM Section 31.5.50.33 documents offset 0x280.  HALCoGen's
 * HL_hw_emac.h defines EMAC_NETOCTETS as 0x208, which collides with
 * RXMCASTFRAMES - this is a transcription error in the vendor header
 * (see the file header note above).  0x280 is used here.
 */

#define RM57_EMAC_NETOCTETS_OFFSET         0x280
#define RM57_EMAC_RXSOFOVERRUNS_OFFSET     0x284
#define RM57_EMAC_RXMOFOVERRUNS_OFFSET     0x288
#define RM57_EMAC_RXDMAOVERRUNS_OFFSET     0x28c

#define RM57_EMAC_MACADDRLO_OFFSET   0x500
#define RM57_EMAC_MACADDRHI_OFFSET   0x504
#define RM57_EMAC_MACINDEX_OFFSET    0x508

#define RM57_EMAC_TXHDP_OFFSET(n)    (0x600 + ((n) << 2))
#define RM57_EMAC_RXHDP_OFFSET(n)    (0x620 + ((n) << 2))
#define RM57_EMAC_TXCP_OFFSET(n)     (0x640 + ((n) << 2))
#define RM57_EMAC_RXCP_OFFSET(n)     (0x660 + ((n) << 2))

/* EMAC Register Addresses ***************************************************/

#define RM57_EMAC_TXREVID            (RM57_EMAC_BASE + RM57_EMAC_TXREVID_OFFSET)
#define RM57_EMAC_TXCONTROL          (RM57_EMAC_BASE + RM57_EMAC_TXCONTROL_OFFSET)
#define RM57_EMAC_TXTEARDOWN         (RM57_EMAC_BASE + RM57_EMAC_TXTEARDOWN_OFFSET)
#define RM57_EMAC_RXREVID            (RM57_EMAC_BASE + RM57_EMAC_RXREVID_OFFSET)
#define RM57_EMAC_RXCONTROL          (RM57_EMAC_BASE + RM57_EMAC_RXCONTROL_OFFSET)
#define RM57_EMAC_RXTEARDOWN         (RM57_EMAC_BASE + RM57_EMAC_RXTEARDOWN_OFFSET)
#define RM57_EMAC_TXINTSTATRAW       (RM57_EMAC_BASE + RM57_EMAC_TXINTSTATRAW_OFFSET)
#define RM57_EMAC_TXINTSTATMASKED    (RM57_EMAC_BASE + RM57_EMAC_TXINTSTATMASKED_OFFSET)
#define RM57_EMAC_TXINTMASKSET       (RM57_EMAC_BASE + RM57_EMAC_TXINTMASKSET_OFFSET)
#define RM57_EMAC_TXINTMASKCLEAR     (RM57_EMAC_BASE + RM57_EMAC_TXINTMASKCLEAR_OFFSET)
#define RM57_EMAC_MACINVECTOR        (RM57_EMAC_BASE + RM57_EMAC_MACINVECTOR_OFFSET)
#define RM57_EMAC_MACEOIVECTOR       (RM57_EMAC_BASE + RM57_EMAC_MACEOIVECTOR_OFFSET)
#define RM57_EMAC_RXINTSTATRAW       (RM57_EMAC_BASE + RM57_EMAC_RXINTSTATRAW_OFFSET)
#define RM57_EMAC_RXINTSTATMASKED    (RM57_EMAC_BASE + RM57_EMAC_RXINTSTATMASKED_OFFSET)
#define RM57_EMAC_RXINTMASKSET       (RM57_EMAC_BASE + RM57_EMAC_RXINTMASKSET_OFFSET)
#define RM57_EMAC_RXINTMASKCLEAR     (RM57_EMAC_BASE + RM57_EMAC_RXINTMASKCLEAR_OFFSET)
#define RM57_EMAC_MACINTSTATRAW      (RM57_EMAC_BASE + RM57_EMAC_MACINTSTATRAW_OFFSET)
#define RM57_EMAC_MACINTSTATMASKED   (RM57_EMAC_BASE + RM57_EMAC_MACINTSTATMASKED_OFFSET)
#define RM57_EMAC_MACINTMASKSET      (RM57_EMAC_BASE + RM57_EMAC_MACINTMASKSET_OFFSET)
#define RM57_EMAC_MACINTMASKCLEAR    (RM57_EMAC_BASE + RM57_EMAC_MACINTMASKCLEAR_OFFSET)
#define RM57_EMAC_RXMBPENABLE        (RM57_EMAC_BASE + RM57_EMAC_RXMBPENABLE_OFFSET)
#define RM57_EMAC_RXUNICASTSET       (RM57_EMAC_BASE + RM57_EMAC_RXUNICASTSET_OFFSET)
#define RM57_EMAC_RXUNICASTCLEAR     (RM57_EMAC_BASE + RM57_EMAC_RXUNICASTCLEAR_OFFSET)
#define RM57_EMAC_RXMAXLEN           (RM57_EMAC_BASE + RM57_EMAC_RXMAXLEN_OFFSET)
#define RM57_EMAC_RXBUFFEROFFSET     (RM57_EMAC_BASE + RM57_EMAC_RXBUFFEROFFSET_OFFSET)
#define RM57_EMAC_RXFILTERLOWTHRESH  (RM57_EMAC_BASE + RM57_EMAC_RXFILTERLOWTHRESH_OFFSET)
#define RM57_EMAC_RXFLOWTHRESH(n)    (RM57_EMAC_BASE + RM57_EMAC_RXFLOWTHRESH_OFFSET(n))
#define RM57_EMAC_RXFREEBUFFER(n)    (RM57_EMAC_BASE + RM57_EMAC_RXFREEBUFFER_OFFSET(n))
#define RM57_EMAC_MACCONTROL         (RM57_EMAC_BASE + RM57_EMAC_MACCONTROL_OFFSET)
#define RM57_EMAC_MACSTATUS          (RM57_EMAC_BASE + RM57_EMAC_MACSTATUS_OFFSET)
#define RM57_EMAC_EMCONTROL          (RM57_EMAC_BASE + RM57_EMAC_EMCONTROL_OFFSET)
#define RM57_EMAC_FIFOCONTROL        (RM57_EMAC_BASE + RM57_EMAC_FIFOCONTROL_OFFSET)
#define RM57_EMAC_MACCONFIG          (RM57_EMAC_BASE + RM57_EMAC_MACCONFIG_OFFSET)
#define RM57_EMAC_SOFTRESET          (RM57_EMAC_BASE + RM57_EMAC_SOFTRESET_OFFSET)
#define RM57_EMAC_MACSRCADDRLO       (RM57_EMAC_BASE + RM57_EMAC_MACSRCADDRLO_OFFSET)
#define RM57_EMAC_MACSRCADDRHI       (RM57_EMAC_BASE + RM57_EMAC_MACSRCADDRHI_OFFSET)
#define RM57_EMAC_MACHASH1           (RM57_EMAC_BASE + RM57_EMAC_MACHASH1_OFFSET)
#define RM57_EMAC_MACHASH2           (RM57_EMAC_BASE + RM57_EMAC_MACHASH2_OFFSET)
#define RM57_EMAC_BOFFTEST           (RM57_EMAC_BASE + RM57_EMAC_BOFFTEST_OFFSET)
#define RM57_EMAC_TPACETEST          (RM57_EMAC_BASE + RM57_EMAC_TPACETEST_OFFSET)
#define RM57_EMAC_RXPAUSE            (RM57_EMAC_BASE + RM57_EMAC_RXPAUSE_OFFSET)
#define RM57_EMAC_TXPAUSE            (RM57_EMAC_BASE + RM57_EMAC_TXPAUSE_OFFSET)

#define RM57_EMAC_RXGOODFRAMES       (RM57_EMAC_BASE + RM57_EMAC_RXGOODFRAMES_OFFSET)
#define RM57_EMAC_RXBCASTFRAMES      (RM57_EMAC_BASE + RM57_EMAC_RXBCASTFRAMES_OFFSET)
#define RM57_EMAC_RXMCASTFRAMES      (RM57_EMAC_BASE + RM57_EMAC_RXMCASTFRAMES_OFFSET)
#define RM57_EMAC_RXPAUSEFRAMES      (RM57_EMAC_BASE + RM57_EMAC_RXPAUSEFRAMES_OFFSET)
#define RM57_EMAC_RXCRCERRORS        (RM57_EMAC_BASE + RM57_EMAC_RXCRCERRORS_OFFSET)
#define RM57_EMAC_RXALIGNCODEERRORS  (RM57_EMAC_BASE + RM57_EMAC_RXALIGNCODEERRORS_OFFSET)
#define RM57_EMAC_RXOVERSIZED        (RM57_EMAC_BASE + RM57_EMAC_RXOVERSIZED_OFFSET)
#define RM57_EMAC_RXJABBER           (RM57_EMAC_BASE + RM57_EMAC_RXJABBER_OFFSET)
#define RM57_EMAC_RXUNDERSIZED       (RM57_EMAC_BASE + RM57_EMAC_RXUNDERSIZED_OFFSET)
#define RM57_EMAC_RXFRAGMENTS        (RM57_EMAC_BASE + RM57_EMAC_RXFRAGMENTS_OFFSET)
#define RM57_EMAC_RXFILTERED         (RM57_EMAC_BASE + RM57_EMAC_RXFILTERED_OFFSET)
#define RM57_EMAC_RXQOSFILTERED      (RM57_EMAC_BASE + RM57_EMAC_RXQOSFILTERED_OFFSET)
#define RM57_EMAC_RXOCTETS           (RM57_EMAC_BASE + RM57_EMAC_RXOCTETS_OFFSET)
#define RM57_EMAC_TXGOODFRAMES       (RM57_EMAC_BASE + RM57_EMAC_TXGOODFRAMES_OFFSET)
#define RM57_EMAC_TXBCASTFRAMES      (RM57_EMAC_BASE + RM57_EMAC_TXBCASTFRAMES_OFFSET)
#define RM57_EMAC_TXMCASTFRAMES      (RM57_EMAC_BASE + RM57_EMAC_TXMCASTFRAMES_OFFSET)
#define RM57_EMAC_TXPAUSEFRAMES      (RM57_EMAC_BASE + RM57_EMAC_TXPAUSEFRAMES_OFFSET)
#define RM57_EMAC_TXDEFERRED         (RM57_EMAC_BASE + RM57_EMAC_TXDEFERRED_OFFSET)
#define RM57_EMAC_TXCOLLISION        (RM57_EMAC_BASE + RM57_EMAC_TXCOLLISION_OFFSET)
#define RM57_EMAC_TXSINGLECOLL       (RM57_EMAC_BASE + RM57_EMAC_TXSINGLECOLL_OFFSET)
#define RM57_EMAC_TXMULTICOLL        (RM57_EMAC_BASE + RM57_EMAC_TXMULTICOLL_OFFSET)
#define RM57_EMAC_TXEXCESSIVECOLL    (RM57_EMAC_BASE + RM57_EMAC_TXEXCESSIVECOLL_OFFSET)
#define RM57_EMAC_TXLATECOLL         (RM57_EMAC_BASE + RM57_EMAC_TXLATECOLL_OFFSET)
#define RM57_EMAC_TXUNDERRUN         (RM57_EMAC_BASE + RM57_EMAC_TXUNDERRUN_OFFSET)
#define RM57_EMAC_TXCARRIERSENSE     (RM57_EMAC_BASE + RM57_EMAC_TXCARRIERSENSE_OFFSET)
#define RM57_EMAC_TXOCTETS           (RM57_EMAC_BASE + RM57_EMAC_TXOCTETS_OFFSET)
#define RM57_EMAC_FRAME64            (RM57_EMAC_BASE + RM57_EMAC_FRAME64_OFFSET)
#define RM57_EMAC_FRAME65T127        (RM57_EMAC_BASE + RM57_EMAC_FRAME65T127_OFFSET)
#define RM57_EMAC_FRAME128T255       (RM57_EMAC_BASE + RM57_EMAC_FRAME128T255_OFFSET)
#define RM57_EMAC_FRAME256T511       (RM57_EMAC_BASE + RM57_EMAC_FRAME256T511_OFFSET)
#define RM57_EMAC_FRAME512T1023      (RM57_EMAC_BASE + RM57_EMAC_FRAME512T1023_OFFSET)
#define RM57_EMAC_FRAME1024TUP       (RM57_EMAC_BASE + RM57_EMAC_FRAME1024TUP_OFFSET)
#define RM57_EMAC_NETOCTETS          (RM57_EMAC_BASE + RM57_EMAC_NETOCTETS_OFFSET)
#define RM57_EMAC_RXSOFOVERRUNS      (RM57_EMAC_BASE + RM57_EMAC_RXSOFOVERRUNS_OFFSET)
#define RM57_EMAC_RXMOFOVERRUNS      (RM57_EMAC_BASE + RM57_EMAC_RXMOFOVERRUNS_OFFSET)
#define RM57_EMAC_RXDMAOVERRUNS      (RM57_EMAC_BASE + RM57_EMAC_RXDMAOVERRUNS_OFFSET)

#define RM57_EMAC_MACADDRLO          (RM57_EMAC_BASE + RM57_EMAC_MACADDRLO_OFFSET)
#define RM57_EMAC_MACADDRHI          (RM57_EMAC_BASE + RM57_EMAC_MACADDRHI_OFFSET)
#define RM57_EMAC_MACINDEX           (RM57_EMAC_BASE + RM57_EMAC_MACINDEX_OFFSET)

#define RM57_EMAC_TXHDP(n)           (RM57_EMAC_BASE + RM57_EMAC_TXHDP_OFFSET(n))
#define RM57_EMAC_RXHDP(n)           (RM57_EMAC_BASE + RM57_EMAC_RXHDP_OFFSET(n))
#define RM57_EMAC_TXCP(n)            (RM57_EMAC_BASE + RM57_EMAC_TXCP_OFFSET(n))
#define RM57_EMAC_RXCP(n)            (RM57_EMAC_BASE + RM57_EMAC_RXCP_OFFSET(n))

/* EMAC_TXCONTROL / RXCONTROL */

#define EMAC_TXCONTROL_TXEN          (1 << 0)
#define EMAC_RXCONTROL_RXEN          (1 << 0)

/* EMAC_TXTEARDOWN / RXTEARDOWN */

#define EMAC_TEARDOWN_CH_SHIFT       0
#define EMAC_TEARDOWN_CH_MASK        (7 << EMAC_TEARDOWN_CH_SHIFT)
#define EMAC_TEARDOWN_CH(n)          (((n) & 7) << EMAC_TEARDOWN_CH_SHIFT)

/* EMAC_TXINTSTATRAW / TXINTSTATMASKED / TXINTMASKSET / TXINTMASKCLEAR -
 * one bit per TX channel 0-7
 */

#define EMAC_TXCH(n)                 (1 << (n))

/* EMAC_RXINTSTATRAW / RXINTSTATMASKED / RXINTMASKSET / RXINTMASKCLEAR -
 * bits 0-7 = RX channel pend, bits 8-15 = RX channel threshold pend
 */

#define EMAC_RXCH(n)                 (1 << (n))
#define EMAC_RXCH_THRESH(n)          (1 << ((n) + 8))

/* EMAC_MACINVECTOR - Section 31.5.11 */

#define EMAC_MACINVECTOR_RXPEND_SHIFT       0
#define EMAC_MACINVECTOR_RXPEND_MASK        (0xff << EMAC_MACINVECTOR_RXPEND_SHIFT)
#define EMAC_MACINVECTOR_RXTHRESHPEND_SHIFT 8
#define EMAC_MACINVECTOR_RXTHRESHPEND_MASK  (0xff << EMAC_MACINVECTOR_RXTHRESHPEND_SHIFT)
#define EMAC_MACINVECTOR_TXPEND_SHIFT       16
#define EMAC_MACINVECTOR_TXPEND_MASK        (0xff << EMAC_MACINVECTOR_TXPEND_SHIFT)
#define EMAC_MACINVECTOR_USERINT0    (1 << 24)
#define EMAC_MACINVECTOR_LINKINT0    (1 << 25)
#define EMAC_MACINVECTOR_HOSTPEND    (1 << 26)
#define EMAC_MACINVECTOR_STATPEND    (1 << 27)

/* EMAC_MACEOIVECTOR - Section 31.5.12.  Acknowledge keys written after
 * servicing an interrupt; each key corresponds to one of the four VIM
 * pulse lines this device routes (C0RXTHRESH/C0RX/C0TX/C0MISC).
 */

#define EMAC_MACEOIVECTOR_C0RXTHRESH 0x0
#define EMAC_MACEOIVECTOR_C0RX       0x1
#define EMAC_MACEOIVECTOR_C0TX       0x2
#define EMAC_MACEOIVECTOR_C0MISC     0x3

/* EMAC_RXMBPENABLE - Section 31.5.21 */

#define EMAC_RXMBPENABLE_RXMULTCH_SHIFT   0
#define EMAC_RXMBPENABLE_RXMULTCH_MASK    (7 << EMAC_RXMBPENABLE_RXMULTCH_SHIFT)
#define EMAC_RXMBPENABLE_RXMULTCH(n)      (((n) & 7) << EMAC_RXMBPENABLE_RXMULTCH_SHIFT)
#define EMAC_RXMBPENABLE_RXMULTEN         (1 << 5)
#define EMAC_RXMBPENABLE_RXBROADCH_SHIFT  8
#define EMAC_RXMBPENABLE_RXBROADCH_MASK   (7 << EMAC_RXMBPENABLE_RXBROADCH_SHIFT)
#define EMAC_RXMBPENABLE_RXBROADCH(n)     (((n) & 7) << EMAC_RXMBPENABLE_RXBROADCH_SHIFT)
#define EMAC_RXMBPENABLE_RXBROADEN        (1 << 13)
#define EMAC_RXMBPENABLE_RXPROMCH_SHIFT   16
#define EMAC_RXMBPENABLE_RXPROMCH_MASK    (7 << EMAC_RXMBPENABLE_RXPROMCH_SHIFT)
#define EMAC_RXMBPENABLE_RXPROMCH(n)      (((n) & 7) << EMAC_RXMBPENABLE_RXPROMCH_SHIFT)
#define EMAC_RXMBPENABLE_RXCAFEN          (1 << 21)
#define EMAC_RXMBPENABLE_RXCEFEN          (1 << 22)
#define EMAC_RXMBPENABLE_RXCSFEN          (1 << 23)
#define EMAC_RXMBPENABLE_RXCMFEN          (1 << 24)
#define EMAC_RXMBPENABLE_RXNOCHAIN        (1 << 28)
#define EMAC_RXMBPENABLE_RXQOSEN          (1 << 29)
#define EMAC_RXMBPENABLE_RXPASSCRC        (1 << 30)

/* EMAC_RXUNICASTSET / RXUNICASTCLEAR - one bit per RX channel 0-7 */

#define EMAC_RXUNICAST_CH(n)         (1 << (n))

/* EMAC_MACCONTROL - Section 31.5.29 */

#define EMAC_MACCONTROL_FULLDUPLEX   (1 << 0)
#define EMAC_MACCONTROL_LOOPBACK     (1 << 1)
#define EMAC_MACCONTROL_RXBUFFERFLOWEN (1 << 3)
#define EMAC_MACCONTROL_TXFLOWEN     (1 << 4)
#define EMAC_MACCONTROL_GMIIEN       (1 << 5)
#define EMAC_MACCONTROL_TXPACE       (1 << 6)
#define EMAC_MACCONTROL_TXPTYPE      (1 << 9)
#define EMAC_MACCONTROL_TXSHORTGAPEN (1 << 10)
#define EMAC_MACCONTROL_CMDIDLE      (1 << 11)
#define EMAC_MACCONTROL_RXOWNERSHIP  (1 << 13)
#define EMAC_MACCONTROL_RXOFFLENBLOCK (1 << 14)
#define EMAC_MACCONTROL_RMIISPEED    (1 << 15) /* 1 = 100Mbps, 0 = 10Mbps */

/* EMAC_MACSTATUS - Section 31.5.30 */

#define EMAC_MACSTATUS_TXFLOWACT     (1 << 0)
#define EMAC_MACSTATUS_RXFLOWACT     (1 << 1)
#define EMAC_MACSTATUS_RXQOSACT      (1 << 2)
#define EMAC_MACSTATUS_RXERRCH_SHIFT 8
#define EMAC_MACSTATUS_RXERRCH_MASK  (7 << EMAC_MACSTATUS_RXERRCH_SHIFT)
#define EMAC_MACSTATUS_RXERRCODE_SHIFT 12
#define EMAC_MACSTATUS_RXERRCODE_MASK  (15 << EMAC_MACSTATUS_RXERRCODE_SHIFT)
#define EMAC_MACSTATUS_TXERRCH_SHIFT 16
#define EMAC_MACSTATUS_TXERRCH_MASK  (7 << EMAC_MACSTATUS_TXERRCH_SHIFT)
#define EMAC_MACSTATUS_TXERRCODE_SHIFT 20
#define EMAC_MACSTATUS_TXERRCODE_MASK  (15 << EMAC_MACSTATUS_TXERRCODE_SHIFT)
#define EMAC_MACSTATUS_IDLE          (1u << 31)

/* EMAC_EMCONTROL - Section 31.5.31 */

#define EMAC_EMCONTROL_FREE          (1 << 0)
#define EMAC_EMCONTROL_SOFT          (1 << 1)

/* EMAC_SOFTRESET */

#define EMAC_SOFTRESET_RESET         (1 << 0)

/* EMAC_MACINTSTATRAW / MACINTSTATMASKED / MACINTMASKSET / MACINTMASKCLEAR -
 * Section 31.5.17-31.5.20.  MASKSET/MASKCLEAR are W1S/W1C; STATRAW/
 * STATMASKED are plain read-only status.
 */

#define EMAC_MACINT_STATPEND         (1 << 0)
#define EMAC_MACINT_HOSTPEND         (1 << 1)

/* EMAC_MACADDRLO - Section 31.5.43 */

#define EMAC_MACADDRLO_MACADDR1_SHIFT 0
#define EMAC_MACADDRLO_MACADDR1_MASK  (0xff << EMAC_MACADDRLO_MACADDR1_SHIFT)
#define EMAC_MACADDRLO_MACADDR0_SHIFT 8
#define EMAC_MACADDRLO_MACADDR0_MASK  (0xff << EMAC_MACADDRLO_MACADDR0_SHIFT)
#define EMAC_MACADDRLO_CHANNEL_SHIFT  16
#define EMAC_MACADDRLO_CHANNEL_MASK   (7 << EMAC_MACADDRLO_CHANNEL_SHIFT)
#define EMAC_MACADDRLO_CHANNEL(n)     (((n) & 7) << EMAC_MACADDRLO_CHANNEL_SHIFT)
#define EMAC_MACADDRLO_MATCHFILT      (1 << 19)
#define EMAC_MACADDRLO_VALID          (1 << 20)

/* EMAC_MACADDRHI - MACADDR2 = MSB ... MACADDR5 = LSB of the upper 4 bytes */

#define EMAC_MACADDRHI_MACADDR5_SHIFT 0
#define EMAC_MACADDRHI_MACADDR4_SHIFT 8
#define EMAC_MACADDRHI_MACADDR3_SHIFT 16
#define EMAC_MACADDRHI_MACADDR2_SHIFT 24

/****************************************************************************
 * Public Type Definitions
 ****************************************************************************/

/* CPPI buffer descriptor - SPNU562A Section 31.2.6.4 / 31.2.6.5.  Common
 * layout for both TX and RX descriptors; some flag bits are only valid
 * on one side (noted below).  This structure is naturally 16 bytes with
 * standard ARM alignment (no padding introduced by the compiler); instances
 * live in the EMAC's internal CPPI RAM, which is mapped by this port's MPU
 * as strongly-ordered/non-cacheable device memory (see rm57_mpuinit.h), so
 * no D-cache maintenance is required for descriptor fields - only for the
 * SRAM packet buffers they point to.
 */

struct rm57_emac_desc_s
{
  volatile struct rm57_emac_desc_s *next; /* Next descriptor pointer (0 = last) */
  volatile uint8_t *buffer;               /* Byte-aligned packet buffer pointer */

  /* Word 2: "Buffer Offset(MSW) and Length(LSW)" (TRM Example 31-1).  On
   * this little-endian target the first-declared of a pair of uint16_t
   * fields lands in the word's low half, so buflen (the LSW) has to be
   * declared before bufoff (the MSW) - the reverse of their natural
   * reading order - or the hardware reads buflen as the offset and
   * bufoff as the length.  Getting this backwards has EMAC report a
   * transmit host error with MACSTATUS.TXERRCODE = 5 ("zero buffer
   * length"), since bufoff is always 0.
   */

  volatile uint16_t buflen;               /* Valid bytes in this buffer */
  volatile uint16_t bufoff;               /* Unused leading bytes (SOP desc only) */

  volatile uint32_t flags_pktlen;         /* Flags (bits 31-16) | packet length (bits 15-0) */
};

/* rm57_emac_desc_s.flags_pktlen flag bits (upper 16 bits) */

#define EMAC_DESC_PKTLEN_MASK        0x0000ffff
#define EMAC_DESC_PASSCRC            0x04000000
#define EMAC_DESC_TDOWNCMPLT         0x08000000
#define EMAC_DESC_EOQ                0x10000000
#define EMAC_DESC_OWNER              0x20000000
#define EMAC_DESC_EOP                0x40000000
#define EMAC_DESC_SOP                0x80000000

/* Additional RX-only status flags (valid on the EOP descriptor) */

#define EMAC_DESC_RX_NOMATCH         0x00010000
#define EMAC_DESC_RX_CRCERROR        0x00020000
#define EMAC_DESC_RX_ALIGNERROR      0x00040000
#define EMAC_DESC_RX_CODEERROR       0x00080000
#define EMAC_DESC_RX_OVERRUN         0x00100000
#define EMAC_DESC_RX_CONTROL         0x00200000
#define EMAC_DESC_RX_UNDERSIZED      0x00400000
#define EMAC_DESC_RX_FRAGMENT        0x00800000
#define EMAC_DESC_RX_OVERSIZE        0x01000000
#define EMAC_DESC_RX_JABBER          0x02000000

#endif /* __ARCH_ARM_SRC_RM57_HARDWARE_RM57_ETHERNET_H */
